load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "vhost",
    srcs = [
        "acme_redirect.go",
        "honeypot_emit.go",
        "vhost.go",
    ],
    importpath = "github.com/aquaduct-dev/weft/src/proxy/vhost",
    visibility = ["//visibility:public"],
    deps = [
        "//src/acme",
        "//src/honeypot",
        "//src/internal/util",
        "//src/proxy/vhost/meter",
        "//wireguard",
        "@com_github_rs_zerolog//log",
        "@org_golang_x_crypto//acme/autocert",
    ],
)

go_test(
    name = "vhost_test",
    srcs = [
        "acme_redirect_test.go",
        "honeypot_emit_test.go",
        "path_prefix_test.go",
        "probe_test.go",
        "vhost_race_test.go",
        "vhost_suite_test.go",
        "vhost_test.go",
    ],
    embed = [":vhost"],
    deps = [
        "//src/acme",
        "//src/crypto",
        "//src/honeypot",
        "//src/proxy/vhost/meter",
        "@com_github_onsi_ginkgo_v2//:ginkgo",
        "@com_github_onsi_gomega//:gomega",
        "@com_github_rs_zerolog//log",
    ],
)
