load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "server",
    srcs = [
        "dataplane.go",
        "handlers_acme_redirect.go",
        "handlers_auth.go",
        "handlers_health.go",
        "handlers_metrics.go",
        "handlers_tunnel.go",
        "handlers_version.go",
        "janitor.go",
        "middleware.go",
        "server.go",
        "store.go",
        "types.go",
        "usage_reporter.go",
    ],
    importpath = "github.com/aquaduct-dev/weft/src/server",
    visibility = ["//visibility:public"],
    deps = [
        "//src/acme",
        "//src/crypto",
        "//src/dns",
        "//src/internal/constants",
        "//src/proxy",
        "//src/version",
        "//types",
        "//wireguard",
        "@com_github_golang_jwt_jwt_v4//:jwt",
        "@com_github_rs_zerolog//log",
        "@com_zx2c4_golang_wireguard_wgctrl//wgtypes",
    ],
)

go_test(
    name = "server_test",
    srcs = [
        "handlers_acme_redirect_test.go",
        "handlers_auth_test.go",
        "handlers_metrics_test.go",
        "handlers_tunnel_test.go",
        "handlers_version_test.go",
        "janitor_test.go",
        "store_test.go",
        "test_helpers_test.go",
        "usage_reporter_test.go",
    ],
    embed = [":server"],
    deps = [
        "//src/crypto",
        "//src/internal/constants",
        "//src/version",
        "//types",
        "//wireguard",
        "@com_github_golang_jwt_jwt_v4//:jwt",
        "@com_zx2c4_golang_wireguard_wgctrl//wgtypes",
    ],
)
