load("@rules_shell//shell:sh_library.bzl", "sh_library")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

sh_library(
    name = "lib",
    srcs = ["lib.sh"],
    data = [
        "//:weft",
    ],
)

sh_test(
    name = "test_tcp_tunnel",
    srcs = ["test_tcp_tunnel.sh"],
    env = {
        "PROTO": "tcp",
    },
    deps = [":lib"],
)

sh_test(
    name = "test_http_tunnel",
    srcs = ["test_tcp_tunnel.sh"],
    env = {
        "PROTO": "http",
    },
    deps = [":lib"],
)

sh_test(
    name = "test_https_tunnel",
    srcs = ["test_https_tunnel.sh"],
    data = [
        "test_tcp_tunnel.sh",
    ],
    env = {
        "PROTO": "https",
    },
    deps = [":lib"],
)

sh_test(
    name = "test_udp_tunnel",
    srcs = ["test_udp_tunnel.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_path_rewriting",
    srcs = ["test_path_rewriting.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_matchers_rewriting",
    srcs = ["test_matchers_rewriting.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_header_modifiers",
    srcs = ["test_header_modifiers.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_redirects",
    srcs = ["test_redirects.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_multi_route_cleanup",
    srcs = ["test_multi_route_cleanup.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_tcp_proxy",
    srcs = ["test_tcp_proxy.sh"],
    env = {
        "PROTO": "tcp",
    },
    deps = [":lib"],
)

sh_test(
    name = "test_http_proxy",
    srcs = ["test_tcp_proxy.sh"],
    env = {
        "PROTO": "http",
    },
    deps = [":lib"],
)

sh_test(
    name = "test_udp_proxy",
    srcs = ["test_udp_proxy.sh"],
    env = {
        "PROTO": "udp",
    },
    deps = [":lib"],
)

sh_test(
    name = "test_tunnel_graceful_shutdown",
    srcs = ["test_tunnel_graceful_shutdown.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_billing_reporting",
    srcs = ["test_billing_reporting.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_probe",
    srcs = ["test_probe.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_secret_enforced",
    srcs = ["test_secret_enforced.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_http_default_port",
    srcs = ["test_http_default_port.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_billing_reporting_source_dest",
    srcs = ["test_billing_reporting_source_dest.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_billing_reporting_multi_tunnel",
    srcs = ["test_billing_reporting_multi_tunnel.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_multi_tunnel",
    srcs = ["test_multi_tunnel.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_retries",
    srcs = ["test_retries.sh"],
    deps = [":lib"],
)

sh_test(
    name = "test_mitm",
    srcs = ["test_mitm.sh"],
    deps = [":lib"],
)
