load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "honeypot",
    srcs = [
        "event.go",
        "honeypot.go",
        "http.go",
        "ssh.go",
        "tcp.go",
        "tls.go",
    ],
    importpath = "github.com/aquaduct-dev/weft/src/honeypot",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_rs_zerolog//log",
        "@org_golang_x_crypto//ssh",
    ],
)
